AGENCIA_NOME = "Especially Turismo"
AGENTE_NOME = "Sofia"
AGENTE_AVATAR = "ET"
AGENCIADOR_NOME = "NOME_DO_AGENCIADOR"
AGENCIADOR_WHATSAPP = "WHATSAPP_DO_AGENCIADOR"
ORCAMENTO_MINIMO_QUALIFICACAO = 3000
HORARIO_ATENDIMENTO_INICIO = 8
HORARIO_ATENDIMENTO_FIM = 20

WEBHOOK_URL = ""  # URL para alertas externos (opcional)
DATABASE_PATH = "especially_turismo.db"
ALERTS_PATH = "alerts.json"

# Modelo de IA (Groq)
GROQ_MODEL = "llama-3.3-70b-versatile"
